# Generated by Django 3.2.6 on 2021-08-26 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0014_remove_user_cliente'),
        ('server', '0003_rename_user_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
