# Generated by Django 3.2.6 on 2021-08-27 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20210826_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='documento',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='server.documento'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='producto',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='server.producto'),
        ),
    ]
